namespace VendorProcessManagerV1.Models
{
    /// <summary>
    /// Represents a single instance of a process generated by choosing an existing template. 
    /// </summary>
    public class ProcessInstance
    {
        /// <summary>
        /// Unique identifier for the ProcessInstance
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// The name for this specific process instance. 
        /// It is set by the user but the suggested name is 
        /// a combination of date and template name.
        /// </summary>
        public string InstanceName { get; set; }
        /// <summary>
        /// The link to the originating template for this instance.
        /// </summary>
        public Guid ProcessTemplateId { get; set; }
        /// <summary>
        /// The details of the originating template.
        /// </summary>
        public ProcessTemplate ProcessTemplate { get; set; }
        /// <summary>
        /// The link to the vendor candidate that is being moved throught
        /// the process
        /// </summary>
        public Guid VendorCandidateId { get; set; }
        /// <summary>
        /// The details of the vendor candidate.
        /// </summary>
        public VendorCandidate VendorCandidate { get; set; }
        /// <summary>
        /// The link to the initiator of the process instance.
        /// </summary>
        public string InitiatedById { get; set; }
        /// <summary>
        /// The details of the initiator.
        /// </summary>
        public AppUser InitiatedBy { get; set; }
        /// <summary>
        /// The date the process instance was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }   
        /// <summary>
        /// The date the process was started.
        /// </summary>
        public DateTime? StartDate { get; set; }
        /// <summary>
        /// The date the process is targeted to end.
        /// </summary>
        public DateTime? TargetEndDate { get; set; }
        /// <summary>
        /// The date the process was completed.
        /// </summary>
        public DateTime? ActualEndDate { get; set; }
        /// <summary>
        /// The status of the process instance. 
        /// </summary>
        public ProcessInstanceStatus Status { get; set; }
        /// <summary>
        /// The set of tasks associated with this process instance. 
        /// </summary>
        public ICollection<ProcessTask> Tasks { get; set; }
            = new List<ProcessTask>(); 
    }

    /// <summary>
    /// The list of possible statuses. 
    /// </summary>
    public enum ProcessInstanceStatus
    {
        NotStarted, 
        InProgress, 
        Completed, 
        Cancelled
    }
}
